Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-007855ac798b5175e
      KeyName: springcicd
      SecurityGroupIds:
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y default-jdk git maven
          sudo mkdir /opt/demo
          sudo chown ubuntu:ubuntu /opt/demo
          cd /opt/demo
          git clone https://github.com/ahmedatef00/Spring-ClCD.git
          cd Spring-ClCD/demo
          mvn package
          nohup java -jar target/demo-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic from public internet
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

