Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      KeyName: your_key_name
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y java-1.8.0-openjdk
          sudo mkdir /opt/demo
          sudo chown ec2-user:ec2-user /opt/demo
          cd /opt/demo
          git clone https://github.com/your_github_repo/demo.git
          cd demo
          mvn package
          java -jar build/libs/demo.jar

Outputs:
  WebsiteURL:
    Value: !Sub "http://${EC2Instance.PublicIp}:8080"
    Description: URL for the demo application
