---
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-007855ac798b5175e"
      InstanceType: "t2.micro"
      KeyName: !Ref DeployerKey
      SecurityGroupIds:
        - !Ref MainSecurityGroup
      Tags:
        - Key: "Name"
          Value: "DeployVM"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Hello, World!" > /tmp/hello.txt

  DeployerKey:
    Type: "AWS::EC2::KeyPair"
    Properties:
      KeyName: !Ref KeyName
      PublicKeyMaterial: !Ref PublicKey

  MainSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Main security group"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"

Parameters:
  KeyName:
    Type: "String"

  PublicKey:
    Type: "String"
    Default: springcicd

Outputs:
  InstancePublicIP:
    Value: !GetAtt EC2Instance.PublicIp
    Description: "Public IP of the EC2 instance"
    Export:
      Name: !Sub "${AWS::StackName}-InstancePublicIP"
