name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          ./mvnw clean package
          ./mvnw test
  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mydockerregistry/myapp:${{ github.sha }}
      - name: Deploy using CloudFormation
        uses: aws-actions/aws-cloudformation-deploy@v1
        with:
          stack-name: my-stack
          template-file: cloudformation/template.yaml
          parameter-overrides: |
            InstanceType=t2.micro
            KeyName=springcicd
            DockerImage=mydockerregistry/myapp:${{ github.sha }}
            S3BucketName=my-s3-bucket-name
          capabilities: CAPABILITY_IAM
          region: us-west-2