name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Verify
        run: |
          cd demo
          mvn -B clean package -DskipTests
          mvn -B clean verify -Pintegration-test
      - name: Print contents of demo/target directory
        run: ls -la demo/target

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            push: true
            tags: mydockerregistry/myapp:${{ github.sha }}
            dockerfile: Dockerfile
            build-args: |
              JAR_FILE=demo/target/demo-0.0.1-SNAPSHOT.jar
            run: |
              cp demo/target/demo-0.0.1-SNAPSHOT.jar .
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name my-stack \
            --template-file packaged-template.yaml \
            --parameter-overrides InstanceType=t2.micro KeyName=springcicd \
            --capabilities CAPABILITY_IAM
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
