name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Verify
        run: |
          cd demo
          mvn -B clean package -DskipTests
          mvn -B clean verify -Pintegration-test
  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package CloudFormation Template
        run: |
          aws cloudformation package \
            --template-file cloudformation/template.yaml \
            --s3-bucket my-s3-bucket-name \
            --output-template-file packaged-template.yaml
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name my-stack \
            --template-file packaged-template.yaml \
            --parameter-overrides InstanceType=t2.micro KeyName=springcicd \
            --capabilities CAPABILITY_IAM
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
