name: CI/CD Pipeline
'on':
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Maven Package
        run: cd demo && mvn -B clean package -DskipTests
      - name: Maven Verify
        run: cd demo && mvn -B clean verify -Pintegration-test
      - name: Print contents of demo/target directory
        run: ls -la demo/target &&pwd
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: demo/target
  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: target
          path: demo/target
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: >-
          ls -la && ls -la demo && cp demo/target/demo-0.0.1-SNAPSHOT.jar ./&& 
          docker build -t ${{ secrets.DOCKER_USER }}/myapp:latest .
      - name: Publish Docker image
        run: 'docker push ${{ secrets.DOCKER_USER }}/myapp:latest'
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name my-stack \
            --template-file cloudformation/template.yaml \
            --parameter-overrides InstanceType=t2.micro KeyName=springcicd \
            --capabilities CAPABILITY_IAM
        env:
          AWS_DEFAULT_REGION: '${{ env.AWS_REGION }}'